Repository Nullify-Platform/cli, pull requests merged in 2023-08, with the labels that each got.

#9 add support for github token exchange api to authenticate with the cli
  README.md
  cmd/cli/main.go
  internal/client/client.go
  internal/client/models.go
  internal/models/auth.go
Labels: minor

#11 use valid golang release version tags and add required labels action
  .github/workflows/ci-require-labels.yml
  .github/workflows/release.yml
Labels: no-release

#12 fix url for sending dast request
  internal/dast/start_scan.go
Labels: patch

#13 Add dast usage
  README.md
  cmd/cli/main.go
  internal/client/client.go
  internal/models/auth.go
Labels: no-release

#14 Add badges and update README
  .github/workflows/scorecard.yml
  Makefile
  README.md
Labels: no-release
